### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by yamamoto-yuta** [RibbonCMS/VanillaTemplate-DEMO#1]
```yaml
blog_title: Vanilla Template - DEMO
site_introduction: This is demo page of VanillaTemplate
copylight_name: RibbonCMS team
copylight_url: https://ribboncms.github.io
root_url: https://ribboncms.github.io/VanillaTemplate-DEMO
issues_page_url: https://github.com/RibbonCMS/VanillaTemplate-DEMO/issues
favicon_image_url: https://github-production-user-asset-6210df.s3.amazonaws.com/55144709/260206505-4249b803-3da9-4d66-8ab1-bc07e58e1d3a.png
author_name: RibbonCMS team
author_introduction: We are RibbonCMS team.
```
