### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by yamamoto-yuta** [RibbonCMS/VanillaTemplate-DEMO#2]
```yaml
site_description: |-
  # のページは何？
  - RibbonCMS のフロントエンドテンプレート "VanillaTemplate" のデモページです。
site_header_title: "VanillaTemplate - DEMO"
```
